### ISSUE TITLE
[Bug Report]: Error: EBUSY: resource busy or locked after PDF conversion

### ISSUE THREAD

**Issue by Sawalhah** [carboneio/carbone#101]
**Environment**
Carbone Version: carbone@2.1.1
Node Version: Node v12.18.0
Desktop OS: Windows 10 x64
Other: LibreOffice: 7.0.2

I've started a PDF generation test, the document generated but I get an error

```internal/fs/utils.js:230
    throw err;
    ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\{user}\AppData\Local\Temp\_office_c_1603106270380_5444_1\user\extensions\bundled\extensions.pmap'
    at Object.unlinkSync (fs.js:1129:3)
    at Object.rmDirRecursive (E:\carbone\node_modules\carbone\lib\helper.js:103:12)
    at Object.rmDirRecursive (E:\carbone\node_modules\carbone\lib\helper.js:107:14)
    at Object.rmDirRecursive (E:\carbone\node_modules\carbone\lib\helper.js:107:14)
    at Object.rmDirRecursive (E:\carbone\node_modules\carbone\lib\helper.js:107:14)
    at Object.exit (E:\carbone\node_modules\carbone\lib\converter.js:114:18)
    at process.<anonymous> (E:\carbone\node_modules\carbone\lib\converter.js:652:13)
    at process.emit (events.js:315:20)
    at process.exit (internal/process/per_thread.js:167:15)
    at E:\carbone\main.js:36:15 {
  errno: -4082,
  syscall: 'unlink',
  code: 'EBUSY',
  path: 'C:\\Users\\{USER}\\AppData\\Local\\Temp\\_office_c_1603106270380_5444_1\\user\\extensions\\bundled\\extensions.pmap'
}

**Comment by steevepay** [comment]
Hello @Sawalhah, thank you for reporting the issue, I also got an issue to generate a PDF on Windows.
Time to investigate.

**Comment by NTTAKR** [comment]
Any news on this issue? Still happening with current versions available and the simplest pdf generation.

**Comment by NyanCetch** [comment]
Found a workaround on Windows to get around this problem. In short, the problem arises in the exit method in the converter.js file when time folders are deleted from the Temp folder. The LibreOffice process does not have time to release the files that must be deleted in time. Therefore, it was decided to comment on the code section that removes these time folders at the time the process is closing. Instead of this path, temporary folders are saved to a text file. In a separate script, we read these paths and delete everything that should have been deleted, after which we delete this file with the paths.

**converter.js**
```
var cleanupPaths = [];
for (var i in conversionFactory) {
  var _factory = conversionFactory[i];
  // if a factory is running
  if (_factory && (_factory.pythonThread !== null || _factory.officeThread !== null)) {
    clearTimeout(_factory.timeoutId);
    _factory.exitCallback = factoryExitFn;
    // kill Python thread first.
    if (_factory.pythonThread !== null) {
      _factory.pythonThread.kill('SIGKILL');
    }
    if (_factory.officeThread !== null) {
      _factory.officeThread.kill('SIGKILL');
      cleanupPaths = cleanupPaths.concat(_factory.userCachePath);
      // helper.rmDirRecursive(_factory.userCachePath);
    }
  }
}

fs.writeFileSync('user_cache.json', JSON.stringify(cleanupPaths));
```

**cleanup_cache.js**
```
var fs = require('fs');
var helper = require('./node_modules/carbone/lib/helper');


var jsonFile = 'user_cache.json';

try {
    // check if file exists
    if (fs.existsSync(jsonFile)) {
        console.log('Found cleanup file!');

        // read json
        var jsonData = fs.readFileSync(jsonFile);
        var cleanupPaths = JSON.parse(jsonData);

        console.log('Clean started...');

        // remove dirs
        for (var i in cleanupPaths) {
            helper.rmDirRecursive(cleanupPaths[i]);
        }
        console.log('Cache dirs cleared!');

        // delete cleanup file
        fs.unlinkSync(jsonFile);
        console.log('Cleanup file deleted!');

        console.log('Clean done!');
    } else {
        console.log('Cleanup file not found. Skip clean!');
    }
} catch(err) {
    console.log(err);
}
```

**Comment by xianguoGou** [comment]
I also encountered the same problem, have you solved it?
