### ISSUE TITLE
Has anyone had any luck integrating with Libreoffice 6.2.x or 6.3.x in a Linux environment?

### ISSUE THREAD

**Issue by ngaldridge** [carboneio/carbone#46]
Hi,

Has anyone had any luck integrating with a Libreoffice 6.2.x or 6.3.x in a linux environment?

I set PYTHONPATH="/usr/lib/libreoffice/program" so that Carbone can find Uno, but I get some strange errors when Carbone's converter.py is attempting to import from com.sun.star...

When I run the test program with Nodejs debug turned on, i get:

```  carbone:converter LibreOffice found: soffice at /usr/lib/libreoffice/program/soffice, python at /usr/bin/python3 +0ms
  carbone:converter python stderr : Traceback (most recent call last):
  File "/usr/local/dcs/node_modules/carbone/lib/converter.py", line 9, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/usr/lib/libreoffice/program/uno.py", line 434, in _uno_import
    raise uno_import_exc
  File "/usr/lib/libreoffice/program/uno.py", line 356, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
 +109ms
  carbone:converter process Python of factory 0 died 1 +4ms
  carbone:converter process Office of factory 0 died null +70ms
  carbone:converter factory 0 is completely off +0ms
  carbone:converter python stderr : Traceback (most recent call last):
  File "/usr/local/dcs/node_modules/carbone/lib/converter.py", line 9, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/usr/lib/libreoffice/program/uno.py", line 434, in _uno_import
    raise uno_import_exc
  File "/usr/lib/libreoffice/program/uno.py", line 356, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
 +101ms
  carbone:converter process Python of factory 0 died 1 +4ms
  carbone:converter process Office of factory 0 died null +289ms
  carbone:converter factory 0 is completely off +0ms
  carbone:converter python stderr : Traceback (most recent call last):
  File "/usr/local/dcs/node_modules/carbone/lib/converter.py", line 9, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/usr/lib/libreoffice/program/uno.py", line 434, in _uno_import
    raise uno_import_exc
  File "/usr/lib/libreoffice/program/uno.py", line 356, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
 +99ms
  carbone:converter process Python of factory 0 died 1 +3ms
```

Thanks in advance for any advice!

Cheers,

Nathan

**Comment by dgrelaud** [comment]
Hi,

How did you install LibreOffice?
We strongly recommend using this method: https://github.com/Ideolys/carbone#on-ubuntu-server--ubuntu-desktop 
This LibreOffice installation method contains everything Carbone needs.

We have some Ubuntu 18.04 LTS servers running successfully with the version  6.3.0.4. Here is the link: http://downloadarchive.documentfoundation.org/libreoffice/old/6.3.0.4/deb/x86_64/LibreOffice_6.3.0.4_Linux_x86-64_deb.tar.gz

Best regards,
David.

**Comment by ngaldridge** [comment]
So, I'm running on Alpine and thus the only binary installs are from the Alpine repo. I guess there's something interesting going on with the Python/LO library integration that I haven't figured out yet.

**Comment by devSwoop** [comment]
I’ve already tried to run Carbone in Alpine for a Docker image, but many things were missing and I didn’t succeed. Good luck with it, it’s hard 😄

**Comment by ngaldridge** [comment]
Ok - I got one run out of it (docker/alpine) - I figured out how the python/libreoffice binding works (at least enough to be dangerous).

I need to do a few more tests now to see if I've really got it.

**Comment by ngaldridge** [comment]
So, I have succeeded in figuring out how to integrate with 6.2.x and 6.3.x in Alpine (in Docker). Feel free to contact me if you would like to know what I had to do.

Cheers!

Nathan

**Comment by pdittaro** [comment]
@ngaldridge I would be interested in this. Are you able to send a gist of your Dockerfile?

**Comment by steevepay** [comment]
Hi,

We are investigating the idea again, we will come back to you.

**Comment by fleebzz** [comment]
Hi @pdittaro 

You can take a look at [carbone-docker](https://hub.docker.com/r/fleebzz/carbone) if you want a packaged Docker image with a Carbone API exposed. (Upgraded to LibreOffice 6.3.3.1 this morning).

You also could be interested in [carbone-connect](https://www.npmjs.com/package/carbone-connect) to have a similar Carbone JS API with some improvements (Promises and Streams).

**Comment by loneil** [comment]
@ngaldridge would you be able to share your Alpine solution? I've got it working with @fleebzz's carbone-docker container (and using newer node images than the 8 one in there), but interested in seeing your Alpine one as well if available. Thanks.

**Comment by loneil** [comment]
> So, I have succeeded in figuring out how to integrate with 6.2.x and 6.3.x in Alpine (in Docker). Feel free to contact me if you would like to know what I had to do.
> 
> Cheers!
> 
> Nathan

@ngaldridge would you be able to share your Alpine solution? I've got it working with @fleebzz's carbone-docker container (and using newer node images than the 8 one in there), but interested in seeing your Alpine one as well if available. Thanks.

**Comment by karimkawambwa** [comment]
I am running into an almost similar issue but the Office is the one that dies.

Anyone with a solution ?
I don't have much details to go with but `dies 1`

```
carbone-lambda_1  | 2022-06-10T14:41:16.622Z carbone:converter process Office of factory 0 died 1
carbone-lambda_1  | 2022-06-10T14:41:16.626Z carbone:converter process Python of factory 0 died null
carbone-lambda_1  | 2022-06-10T14:41:16.627Z carbone:converter factory 0 is completely off
```

**Comment by adussarps** [comment]
[ngaldridge](https://github.com/ngaldridge) I there, could you share the install instruction on docker alpine 🙏 ?
It would be of a great help to :)!

**Comment by enxoco** [comment]
For anyone who may still be trying to get this running in Docker, I recently got this working for a project using `node:20-bulleyes-slim`.  [Here](https://git.hackanooga.com/mikeconrad/slimtoolkit-example/src/branch/master/Dockerfile) is an example Dockerfile that works.  The code included is based on the example code.  The project README describes how you can test it out.  Hopefully this is helpful for someone as I spent about 2-3 days banging my head against a wall trying to get this to work properly.

**Comment by fleebzz** [comment]
After a long time without update I pushed two new versions of [carbone-docker](https://hub.docker.com/r/fleebzz/carbone) with some major upgrades:
- [`fleebzz/carbone:1`](https://hub.docker.com/layers/fleebzz/carbone/1/images/sha256-16f11d5ff0fe27ae87c46fbd4a0dacc0f60101316b28eaf701a7e7f5a2b0f511?context=repo) (which is also the `latest`) based on `bookworm`
- [`fleebzz/carbone:1-slim`](https://hub.docker.com/layers/fleebzz/carbone/1-slim/images/sha256-01313c59e2632f4ec5d736981934e4119983a1da6df91110cea0ff829146ed9e?context=repo) based on `bookworm-slim`

Both versions include these upgrades :
- `node@8` => `node@22`
- `libreoffice@6.3.3.1` => `libreoffice@7.5.1.1`
- `carbone@1.2.0` => `carbone@3.5.6`

Simplest way to integrate this Docker image is to use [carbone-connect](https://www.npmjs.com/package/carbone-connect) to have a similar Carbone JS API that will use a remote Carbone instance and with some improvements (Promises and Streams).

**Comment by steevepay** [comment]
Hello @fleebzz,

For the past year, we've been publishing the latest versions of the Carbone Cloud API as containers on Docker Hub, which you can use for free: [Docker Hub - Carbone](https://hub.docker.com/r/carbone/carbone-ee/tags).

You'll have access to the latest Carbone version 4, featuring LibreOffice 24.8, with or without all fonts pre-installed. By default, it doesn't include enterprise features (such as dynamic pictures, charts, barcodes, etc.). To enable these features, please contact the Carbone team at [support@carbone.io](mailto:support@carbone.io).

When the server starts, you can interact with the following endpoints (the same as the Carbone Cloud API):

- `POST /template`: Upload a template and receive a `templateID`
- `GET /template/`: Download a template
- `DELETE /template/`: Delete a template
- `POST /render/`: Generate a document and receive a unique `renderID`
- `GET /render/`: Download the generated document

To easily interact with the Carbone Server, you can use one of our pre-made SDKs for Javascript, Node, Golang, PHP, and more: [Carbone SDKs](https://github.com/carboneio?q=sdk&type=all&language=&sort=).

Here is the documentation for [Carbone Docker](https://carbone.io/on-premise.html#server-install), where you'll find options and configurations (such as storing templates in S3 or Azure).

**Important announcement:** We are excited to share that we will be releasing Carbone v5 as a Docker container in the coming days. This new version includes an even more efficient engine, numerous bug fixes, and a new DOCX to PDF converter that offers improved accuracy and rendering.
